# Generated by Django 5.2.7 on 2025-11-13 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('emergency_contact', models.CharField(max_length=200)),
                ('emergency_phone_number', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Suspended'), (3, 'Frozen')], default=1)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='gym.gym')),
            ],
            options={
                'ordering': ['-date_joined'],
            },
        ),
    ]
