# Generated by Django 5.2.7 on 2025-12-04 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_gym'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_with_plan', to='memberships.membershipplan'),
        ),
    ]
